modLoader="javafml"
loaderVersion="[36,)"
license="Apache License version 2.0"

[[mods]]
modId="hycwt"
version="0.0.2"
displayName="Hyc's Weird Thoughts"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://hycqwq.top"
authors="hycqwq"
description='''
Some weird thoughts of hyc
'''

[[dependencies.hycwt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




